config/routes.rb
Rails.application.routes.draw do

# This is to make nicer URLs in kaminari
  concern :paginatable do
    get "(page/:page)", action: :index, on: :collection, as: ""
  end

  resources :spirits
  resources :spirit_types
  resources :regions
  resources :distilleries, concerns: :paginatable
  root 'home#index'
  get 'about', to: 'home#about'
  get 'contact', to: 'home#contact'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/spirit_types_controller.rb
class SpiritTypesController < ApplicationController
  before_action :set_spirit_type, only: [:show, :edit, :update, :destroy]

  # GET /spirit_types
  # GET /spirit_types.json
  def index
    @spirit_types = SpiritType.all
  end

  # GET /spirit_types/1
  # GET /spirit_types/1.json
  def show
  end

  # GET /spirit_types/new
  def new
    @spirit_type = SpiritType.new
  end

  # GET /spirit_types/1/edit
  def edit
  end

  # POST /spirit_types
  # POST /spirit_types.json
  def create
    @spirit_type = SpiritType.new(spirit_type_params)

    respond_to do |format|
      if @spirit_type.save
        format.html { redirect_to @spirit_type, notice: 'Spirit type was successfully created.' }
        format.json { render :show, status: :created, location: @spirit_type }
      else
        format.html { render :new }
        format.json { render json: @spirit_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /spirit_types/1
  # PATCH/PUT /spirit_types/1.json
  def update
    respond_to do |format|
      if @spirit_type.update(spirit_type_params)
        format.html { redirect_to @spirit_type, notice: 'Spirit type was successfully updated.' }
        format.json { render :show, status: :ok, location: @spirit_type }
      else
        format.html { render :edit }
        format.json { render json: @spirit_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spirit_types/1
  # DELETE /spirit_types/1.json
  def destroy
    @spirit_type.destroy
    respond_to do |format|
      format.html { redirect_to spirit_types_url, notice: 'Spirit type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_spirit_type
      @spirit_type = SpiritType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def spirit_type_params
      params.require(:spirit_type).permit(:category)
    end
end

app/helpers/spirit_types_helper.rb
module SpiritTypesHelper
end

app/views/spirit_types/_form.html.erb
<%= form_with(model: spirit_type, local: true) do |form| %>
  <% if spirit_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(spirit_type.errors.count, "error") %> prohibited this spirit_type from being saved:</h2>

      <ul>
        <% spirit_type.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/spirit_types/edit.html.erb
<h1>Editing Spirit Type</h1>

<%= render 'form', spirit_type: @spirit_type %>

<%= link_to 'Show', @spirit_type %> |
<%= link_to 'Back', spirit_types_path %>

app/views/spirit_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Spirit Types</h1>

<table>
  <thead>
    <tr>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @spirit_types.each do |spirit_type| %>
      <tr>
        <td><%= spirit_type.category %></td>
        <td><%= link_to 'Show', spirit_type %></td>
        <td><%= link_to 'Edit', edit_spirit_type_path(spirit_type) %></td>
        <td><%= link_to 'Destroy', spirit_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Spirit Type', new_spirit_type_path %>

app/views/spirit_types/new.html.erb
<h1>New Spirit Type</h1>

<%= render 'form', spirit_type: @spirit_type %>

<%= link_to 'Back', spirit_types_path %>

app/views/spirit_types/show.html.erb
<%= render "menubar" %>

<body class="mx-auto container">

  <h1><%= @spirit_type.category %></h1>


<table class="table">
  <thead>
    <tr>
      <th scope="col">Spirit</th>
      <th scope="col">Distillery</th>
      <th scope="col">Proof</th>
    </tr>
  </thead>

  <tbody>
    <% Spirit.all.where(spirit_type_id: @spirit_type.id).each do |s| %>
    <tr>
      <td scope="row"><%= link_to s.name, spirit_path(s) %></td>
      <td scope="row"><%= link_to Distillery.find(s.distillery_id).name, Distillery.find(s.distillery_id) %></td>
      <td scope="row"><%= s.proof %></td>
    </tr>
    <% end %>
  </tbody>
</table>
</body>