config/routes.rb
Rails.application.routes.draw do

# This is to make nicer URLs in kaminari
  concern :paginatable do
    get "(page/:page)", action: :index, on: :collection, as: ""
  end

  resources :spirits
  resources :spirit_types
  resources :regions
  resources :distilleries, concerns: :paginatable
  root 'home#index'
  get 'about', to: 'home#about'
  get 'contact', to: 'home#contact'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/spirit.rb
class Spirit < ApplicationRecord
  belongs_to :distillery
  belongs_to :spirit_type
end

app/models/spirit_type.rb
class SpiritType < ApplicationRecord
end

app/controllers/spirits_controller.rb
class SpiritsController < ApplicationController
  before_action :set_spirit, only: [:show, :edit, :update, :destroy]

  # GET /spirits
  # GET /spirits.json
  def index
    @spirits = Spirit.all
  end

  # GET /spirits/1
  # GET /spirits/1.json
  def show
  end

  # GET /spirits/new
  def new
    @spirit = Spirit.new
  end

  # GET /spirits/1/edit
  def edit
  end

  # POST /spirits
  # POST /spirits.json
  def create
    @spirit = Spirit.new(spirit_params)

    respond_to do |format|
      if @spirit.save
        format.html { redirect_to @spirit, notice: 'Spirit was successfully created.' }
        format.json { render :show, status: :created, location: @spirit }
      else
        format.html { render :new }
        format.json { render json: @spirit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /spirits/1
  # PATCH/PUT /spirits/1.json
  def update
    respond_to do |format|
      if @spirit.update(spirit_params)
        format.html { redirect_to @spirit, notice: 'Spirit was successfully updated.' }
        format.json { render :show, status: :ok, location: @spirit }
      else
        format.html { render :edit }
        format.json { render json: @spirit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spirits/1
  # DELETE /spirits/1.json
  def destroy
    @spirit.destroy
    respond_to do |format|
      format.html { redirect_to spirits_url, notice: 'Spirit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_spirit
      @spirit = Spirit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def spirit_params
      params.require(:spirit).permit(:name, :distillery_id, :spirit_type_id, :proof)
    end
end

app/helpers/spirits_helper.rb
module SpiritsHelper
end

app/views/spirits/_form.html.erb
<%= form_with(model: spirit, local: true) do |form| %>
  <% if spirit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(spirit.errors.count, "error") %> prohibited this spirit from being saved:</h2>

      <ul>
        <% spirit.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :distillery_id %>
    <%= form.select :distillery_id, Distillery.order(:name).map {|d| [d.name, d.id] }, prompt:'-' %>
  </div>

  <div class="field">
    <%= form.label :spirit_type_id %>
    <%= form.select :spirit_type_id, SpiritType.order(:category).map {|t| [t.category, t.id] }, prompt:'-' %>
  </div>

  <div class="field">
    <%= form.label :proof %>
    <%= form.text_field :proof %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/spirits/edit.html.erb
<%= render 'menubar' %>

<body class="mx-auto container">

<h1>Editing <%= @spirit.name %></h1>

<%= render 'form', spirit: @spirit %>

<%= link_to 'Show', @spirit %> |
<%= link_to 'Back', spirits_path %>

</body>

app/views/spirits/index.html.erb
<%= render 'menubar' %>

<body class="mx-auto container">

<h1>Spirits</h1>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Distillery</th>
      <th scope="col">Spirit type</th>
      <th scope="col">Proof</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @spirits.each do |spirit| %>
      <tr>
        <td scope="row"><%= link_to spirit.name, spirit %></td>
        <td><%= link_to Distillery.find(spirit.distillery_id).name, Distillery.find(spirit.distillery_id) %></td>
        <td><%= link_to SpiritType.find(spirit.spirit_type_id).category, SpiritType.find(spirit.spirit_type_id) %></td>
        <td><%= spirit.proof %></td>
        <td><%= link_to 'Edit', edit_spirit_path(spirit) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Spirit', new_spirit_path %>


</body>

app/views/spirits/new.html.erb
<%= render 'menubar' %>

<body class="mx-auto container">

<h1>New Spirit</h1>

<%= render 'form', spirit: @spirit %>

<%= link_to 'Back', spirits_path %>

</body>

app/views/spirits/show.html.erb
<%= render 'menubar' %>

<body class="mx-auto container">

<p>
  <strong>Name:</strong>
  <%= @spirit.name %>
</p>

<p>
  <strong>Distillery:</strong>
  <%= link_to Distillery.find(@spirit.distillery_id).name, Distillery.find(@spirit.distillery_id) %>
</p>


<p>
  <strong>Spirit type:</strong>
  <%= link_to SpiritType.find(@spirit.spirit_type_id).category, SpiritType.find(@spirit.spirit_type_id) %>
</p>

<p>
  <strong>Proof:</strong>
  <%= @spirit.proof %>
</p>

<%= link_to 'Edit', edit_spirit_path(@spirit) %> |
<%= link_to 'Back', spirits_path %>


</body>