config/routes.rb
Rails.application.routes.draw do

# This is to make nicer URLs in kaminari
  concern :paginatable do
    get "(page/:page)", action: :index, on: :collection, as: ""
  end

  resources :spirits
  resources :spirit_types
  resources :regions
  resources :distilleries, concerns: :paginatable
  root 'home#index'
  get 'about', to: 'home#about'
  get 'contact', to: 'home#contact'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/region.rb
class Region < ApplicationRecord
  has_many :distilleries
end

app/controllers/regions_controller.rb
class RegionsController < ApplicationController
  before_action :set_region, only: [:show, :edit, :update, :destroy]

  # GET /regions
  # GET /regions.json
  def index
    @regions = Region.all
  end

  # GET /regions/1
  # GET /regions/1.json
  def show
  end

  # GET /regions/new
  def new
    @region = Region.new
  end

  # GET /regions/1/edit
  def edit
  end

  # POST /regions
  # POST /regions.json
  def create
    @region = Region.new(region_params)

    respond_to do |format|
      if @region.save
        format.html { redirect_to @region, notice: 'Region was successfully created.' }
        format.json { render :show, status: :created, location: @region }
      else
        format.html { render :new }
        format.json { render json: @region.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /regions/1
  # PATCH/PUT /regions/1.json
  def update
    respond_to do |format|
      if @region.update(region_params)
        format.html { redirect_to @region, notice: 'Region was successfully updated.' }
        format.json { render :show, status: :ok, location: @region }
      else
        format.html { render :edit }
        format.json { render json: @region.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /regions/1
  # DELETE /regions/1.json
  def destroy
    @region.destroy
    respond_to do |format|
      format.html { redirect_to regions_url, notice: 'Region was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_region
      @region = Region.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def region_params
      params.require(:region).permit(:region)
    end
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/views/regions/_form.html.erb
<%= form_with(model: region, local: true) do |form| %>
  <% if region.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(region.errors.count, "error") %> prohibited this region from being saved:</h2>

      <ul>
        <% region.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :region %>
    <%= form.text_field :region %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/regions/edit.html.erb
<%= render 'menubar' %>

<body class="mx-auto container">
<h1>Editing <%= @region.region %> Region</h1>

<%= render 'form', region: @region %>

<%= link_to 'Show', @region %> |
<%= link_to 'Back', regions_path %>
</body>

app/views/regions/index.html.erb
<%= render "menubar" %>

<body class="mx-auto container">

  <% @regions.each do |region| %>

    <h3><%= region.region %></h3>
    <ul class="list-group list-group-flush">
      <% Distillery.all.where(region_id: region.id).map.sort_by(&:name).each do |d| %>
        <li class="list-group-item">
          <%= link_to d.name, distillery_path(d) %>
        </li>
      <% end %>
    </ul>
    <br>
  <% end %>

<br>
</body>

app/views/regions/new.html.erb
<%= render 'menubar' %>

<body class="mx-auto container">


<h1>New Region</h1>

<%= render 'form', region: @region %>

<%= link_to 'Back', regions_path %>

</body>

app/views/regions/show.html.erb
<%= render 'menubar' %>

<body class="mx-auto container">

<p>
  <strong>Region:</strong>
  <%= @region.region %>
</p>

<% Distillery.all.where(region_id: @region.id).each do |d| %>
<%= link_to d.name, distillery_path(d) %>
<% end %>
<br>
<br>
<%= link_to 'Edit', edit_region_path(@region) %> |
<%= link_to 'Back', regions_path %>

</body>