config/routes.rb
Rails.application.routes.draw do

# This is to make nicer URLs in kaminari
  concern :paginatable do
    get "(page/:page)", action: :index, on: :collection, as: ""
  end

  resources :spirits
  resources :spirit_types
  resources :regions
  resources :distilleries, concerns: :paginatable
  root 'home#index'
  get 'about', to: 'home#about'
  get 'contact', to: 'home#contact'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_menubar.html.erb
<header>
  <nav class="navbar navbar-light bg-light fixed-top justify-content-center ">
    <ul class="navbar  my-auto">
      <%= link_to 'Home', root_path, :class => "nav-link text-light mx-2" %>
      <%= link_to 'About', about_path, :class => "nav-link text-light mx-2" %>
      <%= link_to 'Distilleries', distilleries_path, :class => "nav-link text-light mx-2" %>
      <%= link_to 'Blog', root_path, :class => "nav-link text-light mx-2" %>
      <%= link_to 'Contact', contact_path, :class => "nav-link text-light mx-2" %>
      <%= link_to 'Spirits', spirits_path, :class => "nav-link text-light mx-2" %>
      <%= link_to 'Regions', regions_path, :class => "nav-link text-light mx-2" %>
    </ul>
  </nav>
</header>



<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>


<% if notice %>
  <div  id="notice">
    <div class="alert alert-info alert-dismissible fade show" role="alert">
      <p><%= notice %></p>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  </div>
<% end %>